# نام فایل: .github/workflows/twitter_scraper.yml

name: Twitter Scraper Workflow

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    # --- این دو خط را اضافه کنید ---
    permissions:
      contents: write
    # ---------------------------
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
    - name: 1. Check out repository code
      uses: actions/checkout@v4

    # ... بقیه مراحل بدون تغییر باقی می‌مانند ...

    - name: 6. Commit and push sent_tweets.txt if it changed
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: Update sent tweets list"
        file_pattern: sent_tweets.txt
        commit_user_name: GitHub Actions Bot
        commit_user_email: actions@github.com
        commit_author: GitHub Actions Bot <actions@github.com>
