name: Twitter Scraper Workflow

on:
  schedule:
    # این کد اسکریپت را هر 5 دقیقه یکبار اجرا می‌کند.
    - cron: '*/5 * * * *'
  # این خط به شما اجازه می‌دهد که workflow را به صورت دستی هم از تب Actions اجرا کنید
  workflow_dispatch:

jobs:
  scrape:
  permissions:
  contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 4 # حداکثر زمان اجرا برای هر بار (کمتر از ۵ دقیقه)

    steps:
    - name: 1. Check out repository code
      uses: actions/checkout@v4

    - name: 2. Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 3. Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright requests

    - name: 4. Install Playwright browsers
      run: python -m playwright install --with-deps

    - name: 5. Run the Twitter scraper script
      run: python tweet_forwarder.py

    - name: 6. Commit and push sent_tweets.txt if it changed
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: Update sent tweets list"
        file_pattern: sent_tweets.txt
        commit_user_name: GitHub Actions Bot
        commit_user_email: actions@github.com
        commit_author: GitHub Actions Bot <actions@github.com>
