name: Twitter Scraper Workflow

# تعریف زمان‌بندی و نحوه اجرای ورک‌فلو
on:
  schedule:
    # این کد اسکریپت را هر 5 دقیقه یکبار اجرا می‌کند.
    - cron: '*/5 * * * *'
  # این خط به شما اجازه می‌دهد که ورک‌فلو را به صورت دستی هم از تب Actions اجرا کنید
  workflow_dispatch:

# --- بخش جدید: جلوگیری از اجرای همزمان ---
# این بخش تضمین می‌کند که همیشه فقط یک اجرای این ربات در حال کار باشد
# و از تداخل و خطای non-fast-forward جلوگیری می‌کند.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# تعریف وظایفی که باید انجام شوند
jobs:
  # نام وظیفه (میتواند هر چیزی باشد)
  scrape:
    # اجازه دسترسی برای نوشتن در ریپازیتوری (برای آپدیت فایل sent_tweets.txt)
    permissions:
      contents: write
      
    # تعریف سیستم‌عامل سرور مجازی
    runs-on: ubuntu-latest
    # تعریف حداکثر زمان اجرا برای هر بار
    timeout-minutes: 4

    # تعریف مراحل انجام کار به ترتیب
    steps:
    # مرحله ۱: دانلود کد ریپازیتوری شما روی سرور مجازی
    - name: 1. Check out repository code
      uses: actions/checkout@v4

    # مرحله ۲: نصب و تنظیم نسخه پایتون مورد نیاز
    - name: 2. Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # مرحله ۳: نصب کتابخانه‌های پایتون
    - name: 3. Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright requests

    # مرحله ۴: نصب مرورگرهای مورد نیاز برای Playwright
    - name: 4. Install Playwright browsers
      run: python -m playwright install --with-deps

    # مرحله ۵: اجرای اسکریپت اصلی پایتون شما
    - name: 5. Run the Twitter scraper script
      run: python tweet_forwarder.py # نام فایل پایتون شما

    # مرحله ۶: ذخیره کردن تغییرات در فایل sent_tweets.txt
    - name: 6. Commit and push sent_tweets.txt if it changed
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: Update sent tweets list"
        file_pattern: sent_tweets.txt
        commit_user_name: GitHub Actions Bot
        commit_user_email: actions@github.com
        commit_author: GitHub Actions Bot <actions@github.com>
